### ISSUE TITLE
Check why charm is not working in Openstack

### ISSUE THREAD

**Issue by avimehenwal** [CN-UPB/tng-sdk-benchmark#20]
https://github.com/CN-UPB/pg-backflip/blob/master/screenshots/charm-juju-issue.png

**Comment by bsharma021** [comment]
The charms are now working. There was a problem in the descriptions of the charms. 
In the reactive files of the charm, there was an error in sshproxy.py file.
Change `validated` to `verified`. 
![image](https://user-images.githubusercontent.com/49458380/66219316-38f76e00-e6cb-11e9-99a0-e06230a92856.png)
