### ISSUE TITLE
Research OSM API connection

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#3]
Research and experiment with the OSM API connection and write ideas on how a possible connection can be created with tng-bench

**Comment by qarawlus** [comment]
Current ideas in for OSM NBI function calls:
- GET tenant and datacenter information (here: OpenStack)
- POST VNF in a tenant
- POST a new scenario with the VNF with deploy, start, or reserve.
- POST action on an instance
- GET instance IP address of the VM

Afterwards, we can SSH into the VM to get performance data. This is an initial thought of mine as of now and can be changed upon further research. 

One challenge that I believe we will face is sending requests in multiple formats. I saw that doing POST on instances requires sending YAML requests, while the rest send requests using JSON.

**Comment by avimehenwal** [comment]
* [Instructions on How to install NBI](https://osm.etsi.org/wikipub/index.php/Developer_HowTo)
* ~I think `pyang` already has modules/functions to transform `JSON to YAML` and vice-versa.~
`yang` is `NETCONF` parser

**Comment by SuganthiJagan** [comment]
Also, we could use PyYAML package for converting from JSON to YAML.

**Comment by SuganthiJagan** [comment]
To get performance/identity data, a suggestion could be using LDAP in common service call. But need to research further on its feasibility.

**Comment by SuganthiJagan** [comment]
https://osm.etsi.org/wikipub/index.php/OSM_Integration_Guidelines

**Comment by qarawlus** [comment]
Complete API documentation 
https://osm.etsi.org/wikipub/index.php/NBI_API_Description

**Comment by avimehenwal** [comment]
Here is a documentation of NBI API call which I have tested

https://documenter.getpostman.com/view/8208840/SVYqPJoK?version=latest

> [cURL command for request](https://github.com/CN-UPB/tng-sdk-benchmark/wiki/NBI-API)

![Screenshot from 2019-08-04 21-44-28](https://user-images.githubusercontent.com/3624059/62428396-c3d6df00-b701-11e9-9736-4addb4ac4efb.png)

PS: I think we should unpublish the documentation after some time as it has username and passwords!?
