### ISSUE TITLE
Research tng-bench source code

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#4]
Research and experiment with the tng-bench source code and write ideas on how a development with OSM can take place and which functionality should be added.

**Comment by bsharma021** [comment]
The main code part of tng-bench to be edited is the 'executor.py' file along with its relation with vimemu. We will be creating a new p_driver, similar to vimemu-pdriver. Generating experiments would stay the same but with some wrapping modifications to alter it according to the new driver. Rest processes of setting up of platform and setting up, execution and teardown of experiments will be modified according to the new infrastructure of OpenStack and OSM. 
The exact flow of the existing code can be seen in the attached sequence diagram.
![Sequence Diagram - tng-sdk-benchmark](https://user-images.githubusercontent.com/49458380/62405627-07b1d300-b5a0-11e9-9c56-8fa97a677fad.png)
