### ISSUE TITLE
Write OSM driver design document

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#5]
After writing initial ideas is finished, the driver design document should be written.

It should contain the following (list can be updated):
- Expected technical architecture to be used
- Style of development 
- Expected API calls
- Flow diagrams

@team Feel free to add more items if you think I missed something.

**Comment by Harshita-Puri** [comment]
I'd further propose the following outline to be merged with the current one.

**Overview** /**Purpose**- What is supposed to be done, why are we doing it?
**In-depth architectural description**
**Design Idea**- What will we do?
**Technical details**- How will we do it, including the code flow
**Risks**
**Relevance in time plan** - When will we do it
**Team members**- Who will do it
**Relevant structural diagrams**
**Revision history**

**Comment by Harshita-Puri** [comment]
[Design Doc data.txt](https://github.com/CN-UPB/tng-sdk-benchmark/files/3463072/Design.Doc.data.txt)

Guys, I have prepared a doc stating ideas that I know of. It also contains some statements from the Project Plan which might need revision. Someone please create a Latex file so that we can put all this in that file. Since, I didn't have the template, I've put it in a text file.  Any suggestions for the outline/work are welcome.

**Comment by SuganthiJagan** [comment]
@Harshita-Puri , yes i could create a latex file and merge the content.

**Comment by SuganthiJagan** [comment]
Hey guys, I have created the template for design document (also added some content) and here is the link,
https://www.overleaf.com/9419262396hqzndzyjvsws
Have also shared it via email. Feel free to modify.

**Comment by SuganthiJagan** [comment]
Hello all, I have created a diagram for the initial tng-to-osm connection. I have also updated the Driver design document to the current needs which could be considered as the initial version.
Please feel free to modify. Here is the link,
[https://www.overleaf.com/project/5d46d66467573e3c760eb13d](url)

**Comment by qarawlus** [comment]
Hi, I just added content to the technical details section and the driver development phases.

**Comment by SuganthiJagan** [comment]
![Tng-OSM (4)](https://user-images.githubusercontent.com/49244398/63258375-89d91180-c299-11e9-9e96-c3efddd73fff.png)
I have enhanced the diagram for proposed design and also added other relevant details to the section.

**Comment by SuganthiJagan** [comment]
I have enhanced further the diagram for proposed design and added other relevant details to the section.

**Comment by SuganthiJagan** [comment]
![Tng-OSM (4)](https://user-images.githubusercontent.com/49244398/63265812-1260ad80-c2ac-11e9-9a6e-abd2c474f85e.png)
