### ISSUE TITLE
Modify probe (mp) VNFDs in addition to the main VNFD

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#63]
The OSM generator should also modify the VNFD for the measurement points (probes) according to the parameters provided in the PED file. 

The VNFD file is passed already to the generator and is stored in the experiment class. The next task is to pass it to the modifier function to correctly handle the file and modify it.

**Comment by bsharma021** [comment]
Refer #69 
Task Completed
