### ISSUE TITLE
Modify cloud VMs to install packages

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#64]
To provide better documentation of the benchmarking process using VMs, we should try and preinstall software on Openstack images before they are deployed. This should considerably speed up the experiment times since the images are deployed with the required software, and not installed during the execution of the cloudinit script. 

The process of the modification with regards to our scenario should also be well documented.

**Comment by bsharma021** [comment]
Refer [Custom Cloud Image Creation ](https://github.com/CN-UPB/tng-sdk-benchmark/wiki/Create-Custom-Cloud-Image)
Task Completed
